services:
  geth-query:
    image: ethereum/client-go:v1.14.12
    container_name: geth-query
    ports:
      - "8548:8545"
    volumes:
      - ./geth-data:/root/.ethereum
      - ../chain-data:/chain-data
    command:
      - --datadir=/root/.ethereum
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.api=eth,net,web3,debug,admin
      - --http.corsdomain=*
      - --http.vhosts=*
      - --nodiscover
      - --maxpeers=0
      - --verbosity=3
